name: Ebiten Test Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      uses: actions/setup-go@v1
      with:
        go-version: 1.18

    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: make vendor

    - name: Run tests
      run: make cover
